#!/usr/bin/env bash
# Main orchestrator: review a single PR end-to-end.
# Usage: review-pr.sh <pr-number> [--force]
# Exit codes: 0 = reviewed, 2 = skipped (idempotency/trivial), 1 = error
set -uo pipefail

# --- Parse arguments ---
FORCE=false
PR_NUMBER=""
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=true ;;
    *) PR_NUMBER="$arg" ;;
  esac
done

if [ -z "$PR_NUMBER" ]; then
  echo "Usage: review-pr.sh <pr-number> [--force]"
  exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
SKILL_DIR="$REPO_ROOT/skills/auto-pr-review"
WORK_DIR="/tmp/auto-pr-review/${PR_NUMBER}"
ORIGINAL_BRANCH=""
ORIGINAL_SHA=""

# --- Cleanup trap ---
cleanup() {
  echo "--- Cleanup ---"
  if [ -n "$ORIGINAL_BRANCH" ] && [ "$ORIGINAL_BRANCH" != "HEAD" ]; then
    git checkout "$ORIGINAL_BRANCH" 2>/dev/null || true
  elif [ -n "$ORIGINAL_SHA" ]; then
    git checkout "$ORIGINAL_SHA" 2>/dev/null || true
  fi
  # Keep work dir for debugging; batch script can clean up
}
trap cleanup EXIT

echo "=== auto-pr-review: PR #${PR_NUMBER} ==="

# --- Step 1: Safety checks ---
# Check gh auth
if ! gh auth status > /dev/null 2>&1; then
  echo "ERROR: gh not authenticated. Run 'gh auth login' first."
  exit 1
fi

# Check clean working tree
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  echo "ERROR: Working tree is dirty. Stash or commit changes first."
  exit 1
fi

# Record current state
ORIGINAL_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")"
ORIGINAL_SHA="$(git rev-parse HEAD)"

# Create work directory
mkdir -p "$WORK_DIR"

# --- Step 2: Get PR info ---
PR_SHA=$(gh pr view "$PR_NUMBER" --json headRefOid --jq '.headRefOid' 2>/dev/null || echo "")
if [ -z "$PR_SHA" ]; then
  echo "ERROR: Could not fetch PR #${PR_NUMBER}. Does it exist?"
  exit 1
fi
echo "$PR_SHA" > "$WORK_DIR/pr-sha.txt"
echo "PR SHA: $PR_SHA"

# --- Step 3: Idempotency check ---
EXISTING=$(gh pr view "$PR_NUMBER" --json comments \
  --jq "[.comments[].body | select(contains(\"<!-- auto-pr-review:${PR_SHA} -->\"))] | length" 2>/dev/null || echo "0")

if [ "$EXISTING" -gt 0 ]; then
  echo "PR #${PR_NUMBER} already reviewed at SHA ${PR_SHA}. Skipping."
  exit 2
fi

# --- Step 4: Pre-check analysis ---
if [ "$FORCE" = false ]; then
  echo "--- Pre-check analysis ---"
  PRECHECK_RESULT=$(bash "$SKILL_DIR/scripts/precheck-pr.sh" "$PR_NUMBER" "$WORK_DIR")
  echo "Pre-check result: $PRECHECK_RESULT"

  if [ "$(cat "$WORK_DIR/precheck.txt")" = "skip" ]; then
    echo "PR classified as trivial, posting skip comment..."

    # Get changed files list
    CHANGED_FILES=$(cat "$WORK_DIR/changed-files.txt" 2>/dev/null | head -10 | sed 's/^/- /')
    TOTAL_LINES=$(cat "$WORK_DIR/total-lines.txt" 2>/dev/null || echo "?")

    # Post trivial-change comment
    SKIP_COMMENT="<!-- auto-pr-review:${PR_SHA} -->
## Auto PR Review — Skipped (Trivial Change)

This PR was classified as a trivial change and skipped the full test pipeline.
**Reason:** ${PRECHECK_RESULT#skip:}

**Changed files:**
${CHANGED_FILES}

**Total lines changed:** ${TOTAL_LINES}

---
<sub>Generated by auto-pr-review skill | VibeLab</sub>"

    echo "$SKIP_COMMENT" > "$WORK_DIR/comment.md"
    gh pr comment "$PR_NUMBER" --body-file "$WORK_DIR/comment.md"
    echo "Skip comment posted for PR #${PR_NUMBER}"
    exit 2
  fi
else
  echo "--- Pre-check bypassed (--force) ---"
fi

# --- Step 5: Checkout PR ---
echo "--- Checking out PR #${PR_NUMBER} ---"
git fetch origin > /dev/null 2>&1
gh pr checkout "$PR_NUMBER" --detach 2>/dev/null
if [ $? -ne 0 ]; then
  echo "ERROR: Failed to checkout PR #${PR_NUMBER}"
  exit 1
fi

# --- Step 6: Classify PR ---
echo "--- Classifying PR ---"
CLASSIFY_RESULT=$(bash "$SKILL_DIR/scripts/classify-pr.sh" "$PR_NUMBER" "$WORK_DIR")
echo "PR type: $CLASSIFY_RESULT"

# --- Step 7: Run mechanical checks ---
echo "--- Running mechanical checks ---"
bash "$SKILL_DIR/scripts/run-checks.sh" "$WORK_DIR"

# --- Step 8: Parse results ---
echo "--- Parsing results ---"
node "$SKILL_DIR/scripts/parse-results.js" \
  --work-dir "$WORK_DIR" \
  --pr-number "$PR_NUMBER" \
  --pr-sha "$PR_SHA" \
  --output "$WORK_DIR/report.json"

# --- Step 9: Invoke agent for comment ---
echo "--- Generating review comment ---"
bash "$SKILL_DIR/scripts/invoke-agent.sh" "$PR_NUMBER" "$WORK_DIR" "$SKILL_DIR"

# --- Step 10: Post comment ---
if [ -f "$WORK_DIR/comment.md" ] && [ -s "$WORK_DIR/comment.md" ]; then
  echo "--- Posting comment ---"
  gh pr comment "$PR_NUMBER" --body-file "$WORK_DIR/comment.md"
  echo "Review comment posted for PR #${PR_NUMBER}"
else
  echo "ERROR: No comment generated for PR #${PR_NUMBER}"
  exit 1
fi

echo "=== auto-pr-review: PR #${PR_NUMBER} complete ==="
